config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root 'recipes#index'
  get 'pages/about'
  get 'welcome/show', to: 'welcome#show'

  resources :recipes, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true

  mount_uploader :image, ImageUploader

end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
  before_action :require_login, only: %i[ new edit update destroy]
  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :description)
      params.require(:recipe).permit(:remove_image, :image, :title, :description, ingredients_attributes:[:id, :content, :_destroy], steps_attributes:[:id, :direction, :_destroy])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "Recipe App", root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li><%= link_to "About", pages_about_path %>
        <li><%= link_to "Sign In", welcome_show_path %>
      </ul>
    </div>
  </nav>

  <body>
    <section>
    <%= yield %>
    </section>
  </body>
</html>

app/views/pages/about.html.erb
<!--Place holder Text-->
<h1>About Page Placeholder</h1>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.file_field :image %>
    <% if @recipe.image? %>
      <%= image_tag @recipe.image.url, class: "recipe-show" %>
      <%= form.check_box :remove_image %>
        Remove Image
    <% end %>
 </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <h3>Add Ingredients</h3>
  <%= form.fields_for :ingredients do |ingredient| %>
  <%= render 'ingredient_fields', f: ingredient %>
  <% end %>
  <div class="links">
  <%= link_to_add_association 'Add Ingredient', form, :ingredients %>
  </div>

  <h3>Add Steps</h3>
  <%= form.fields_for :steps do |step| %>
  <%= render 'step_fields', f: step %>
  <% end %>
  <div class="links">
  <%= link_to_add_association 'Add Step', form, :steps %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
<div class="field">
<%= f.label :content %>

<%= f.text_field :content %>

<%= link_to_remove_association "remove ingredient", f %>
</div>
</div>

app/views/recipes/_step_fields.html.erb
<div class="nested-fields">
<div class="field">
<%= f.label :direction %>

<%= f.text_field :direction %>

<%= link_to_remove_association "remove step", f %>
</div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

    <% @recipes.each do |recipe| %>
      <div class="col-md-4">
      <div class="recipe-box">
      <% if recipe.image? %>
      <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
    <% end %>
    <ul>
        <li><%= recipe.title %></li>
        <li><%= recipe.description %></li>
        <li><%= link_to 'Show', recipe %> |
        <%= link_to 'Edit', edit_recipe_path(recipe) %>
      <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
  </div><!-- /recipe-box-->
</div><!--col-md-4-->
    <% end %>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<% if @recipe.image? %>
<%= image_tag @recipe.image.url, class: "recipe-show" %>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<h3>Ingredients</h3>
<ul>
  <% for @ingredient in @recipe.ingredients %>
    <li><%= @ingredient.content %></li>
  <% end %>
</ul>

<h3>Steps</h3>
<ol>
  <% for @step in @recipe.steps %>
    <li><%= @step.direction %></li>
  <% end %>
</ol>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/welcome/show.html.erb
<header>
  <% if signed_in? %>
    Signed in as: <%= current_user.email %>
    <%= button_to 'Sign out', sign_out_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign in', sign_in_path %>
  <% end %>
</header>
<div id="flash">
 <% flash.each do |key, value| %>
   <div class="flash <%= key %>"><%= value %></div>
 <% end %>
</div>